# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cddb8d739e059b9503a9d64057daedfade02e704064f780d77131175afce8b05a43a1fe95c6752db1501a1363e8c11eb14738653fe6c511cbb0f0fdfba1e898

test:
  secret_key_base: 1035b3cdc88f2ece58129c0c66e0ca5745496ce75f647bc6ba4bc9c9b55a3506e950f3b63cd07fbc5ad23fe56e5c2d1057110ee85be848a40d5b1650209df92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
